version: "3.3"

services:

  push_base:
    image: ilha/rapidpro-base:base
    build:
      context: .
      dockerfile: push_base.Dockerfile
  push_prod:
    image: ilha/rapidpro:prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
